name: ESLint
on: [push, pull_request]

jobs:
  build:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current state of the repo
      uses: actions/checkout@v2

    - name: Install dependencies in CI mode
      run: npm ci

    - name: Lint project using ESLint
      run: npm run lint
